

name: Build docs PDFs
on:
  push:
    branches: [main]
    paths:
      - "docs/**/*.md"
      - ".github/workflows/docs-pdf.yml"
  workflow_dispatch:
jobs:
  md2pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Render Markdown → PDF
        run: |
          mkdir -p artifacts
          shopt -s nullglob
          for f in docs/*.md docs/**/*.md; do
            base="${f%.md}"
            docker run --rm -v "$PWD":/data pandoc/core:3.1 \
              "$f" -o "artifacts/$(basename "$base").pdf" \
              --from=gfm --pdf-engine=xelatex \
              --metadata=title:"$(basename "$base")" \
              --toc --toc-depth=2
          done
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: artifacts/*.pdf
